const fs = require('fs');
const path = require('path');
const os = require('os');

const CLAUDE_DIR = path.join(os.homedir(), '.claude');
const SETTINGS_PATH = path.join(CLAUDE_DIR, 'settings.json');
const SCRIPT_DEST = path.join(CLAUDE_DIR, 'statusline-command.js');

/**
 * Build a self-contained statusline script by bundling all src modules
 * into a single file with a mini module system.
 */
function buildBundle() {
  const srcDir = path.resolve(__dirname);
  const modules = ['bar.js', 'credentials.js', 'usage.js', 'statusline.js'];

  const moduleSources = {};
  for (const mod of modules) {
    moduleSources[mod] = fs.readFileSync(path.join(srcDir, mod), 'utf8');
  }

  // Build the bundled script
  let bundle = `#!/usr/bin/env node
// Auto-generated by cc-usage-statusline — do not edit
// https://www.npmjs.com/package/cc-usage-statusline

const _moduleRegistry = {};
const _moduleCache = {};

function _localRequire(name) {
  // Pass through to real require for Node.js built-ins
  if (!name.startsWith('./')) return require(name);

  // Normalize the name
  const key = name.endsWith('.js') ? name : name + '.js';
  if (_moduleCache[key]) return _moduleCache[key].exports;

  const mod = { exports: {} };
  _moduleCache[key] = mod;

  if (!_moduleRegistry[key]) {
    throw new Error('Module not found: ' + key);
  }
  _moduleRegistry[key](mod, mod.exports, _localRequire);
  return mod.exports;
}

`;

  for (const mod of modules) {
    const src = moduleSources[mod];
    bundle += `_moduleRegistry['./${mod}'] = function(module, exports, require) {\n`;
    bundle += src;
    bundle += `\n};\n\n`;
  }

  bundle += `// Entry point\n`;
  bundle += `_localRequire('./statusline.js');\n`;

  return bundle;
}

function install() {
  // Ensure ~/.claude exists
  if (!fs.existsSync(CLAUDE_DIR)) {
    fs.mkdirSync(CLAUDE_DIR, { recursive: true });
  }

  // Write the bundled statusline script
  const script = buildBundle();
  fs.writeFileSync(SCRIPT_DEST, script, { mode: 0o755 });
  console.log(`\u2713 Wrote statusline script to ${SCRIPT_DEST}`);

  // Patch settings.json
  let settings = {};
  if (fs.existsSync(SETTINGS_PATH)) {
    try {
      settings = JSON.parse(fs.readFileSync(SETTINGS_PATH, 'utf8'));
    } catch {
      // If settings.json is malformed, start fresh but warn
      console.log('\u26a0 Could not parse existing settings.json, creating new one');
    }
  }

  settings.statusLine = {
    type: 'command',
    command: `node "${SCRIPT_DEST}"`,
  };

  fs.writeFileSync(SETTINGS_PATH, JSON.stringify(settings, null, 2) + '\n');
  console.log(`\u2713 Updated ${SETTINGS_PATH}`);
  console.log('\nDone! Restart Claude Code to see your status line.');
}

function uninstall() {
  // Remove script
  if (fs.existsSync(SCRIPT_DEST)) {
    fs.unlinkSync(SCRIPT_DEST);
    console.log(`\u2713 Removed ${SCRIPT_DEST}`);
  } else {
    console.log('No statusline script found.');
  }

  // Clean settings.json
  if (fs.existsSync(SETTINGS_PATH)) {
    try {
      const settings = JSON.parse(fs.readFileSync(SETTINGS_PATH, 'utf8'));
      if (settings.statusLine) {
        delete settings.statusLine;
        fs.writeFileSync(SETTINGS_PATH, JSON.stringify(settings, null, 2) + '\n');
        console.log(`\u2713 Cleaned ${SETTINGS_PATH}`);
      }
    } catch {
      console.log('\u26a0 Could not clean settings.json');
    }
  }
}

function run(args) {
  const cmd = args[0];
  if (cmd === 'install') return install();
  if (cmd === 'uninstall') return uninstall();

  console.log('cc-usage-statusline — Claude Code status line with usage limits\n');
  console.log('Usage: cc-usage-statusline <command>\n');
  console.log('Commands:');
  console.log('  install     Install the status line script and configure Claude Code');
  console.log('  uninstall   Remove the status line script and clean configuration');
  process.exit(cmd ? 1 : 0);
}

module.exports = { run, install, uninstall, buildBundle };
